### ISSUE TITLE
[Bug]: Floating Fan

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#115]
### Describe the bug

Floating Fan is stuck with the bottom case and floating around wherever you turn the waste bottom.
The fan can not be removed and will not be removed to the waste bin. As long as this happen, you are not able to use your workbench.

### Screenshot(s)/Video(s)

![Scrapper_Bug_Fanfloat](https://github.com/FuryFight3r/ScrappingSimulator/assets/6820904/5b11f7e7-b1d6-4f41-9a90-834a62dc7b28)

### Player Logs

[Scrapping_Simulator_Log.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/11582484/Scrapping_Simulator_Log.zip)

**Comment by FuryFight3r** [comment]
Hi there @senoks with this you may be able to press 'F' to stop disassembling, pickup and then drop the laptop back onto the disassembly bench, which should detect the bugged item and remove it allowing you to finish disassembling.
If that fails and or if you are unable to exit disassembly mode due to the fan being bugged then something else may be going wrong that is interfering with the Disassembly. I will look into this and try have a patch out asap providing I can recreate it 🙂👍

**Comment by aus2004** [comment]
this seems to happen a lot with items, it seems to happen when you manage to leave the table while taking the second to last part off, it is really strange and does prevent you from removing the frame, if you take the piece off and put it back on the part will disappear into thin air

**Comment by FuryFight3r** [comment]
Thanks again for reporting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍

**Comment by andyneff** [comment]
I've seen this several times too. I have not found a consistent way to do this yet. Usually the "pickup and then drop" method does work. But on one computer it was a stick of RAM that was stuck, picking up and dropping did not fix it. Even saving and reloading did not fix it. In the end I had to sell it to the PAWN shop as nothing I could try worked. I forgot to check `F5` for notes
